/camera_node:
  ros__parameters:
    camera_info_url: package://rm_vision_bringup/config/camera_info.yaml
    exposure_time: 3000
    gain: 16.0

/serial_driver:
  ros__parameters:
    timestamp_offset: 0.002
    device_name: /dev/ttyACM0
    baud_rate: 115200
    flow_control: none
    parity: none
    stop_bits: "1"

/armor_detector:
  ros__parameters:
    debug: true

    detect_color: 0
    binary_thres: 80

    light.min_ratio: 0.1
    armor.min_light_ratio: 0.8

    classifier_threshold: 0.6
    ignore_classes: ["negative"]

/armor_tracker:
  ros__parameters:
    target_frame: odom
    max_armor_distance: 10.0

    ekf:
      # sigma2_q_xyz: 0.005 #0.005
      # sigma2_q_yaw: 0.0005 #0.005
      # sigma2_q_r: 50.0 #80.0

      # r_xyz_factor: 5e+8 #4e-2
      # r_yaw: 5e+8 #5e+1

      sigma2_q_xyz: 1e12
      sigma2_q_yaw: 1e12
      sigma2_q_r: 1e12

      r_xyz_factor: 5e+8
      r_yaw: 5e+5

    tracker:
      max_match_distance: 0.5
      max_match_yaw_diff: 1.0

      tracking_thres: 5
      lost_time_thres: 0.3
